locusLikes <- function(hypothesis,results) 
	{
	# Generate locus likelihoods from overall likelihood
	#
	# Parameters:
	# 	hypothesis: generated by either defense.hypothesis() or 
        #       prosecution.hypothesis()
	#	results: results from do.call(optim,params)
	model <- create.likelihood.vectors(hypothesis)
	arguments <- relistArguments(results$par, hypothesis)
	likes <- do.call(model,arguments)
	likes <- likes$objectives * likes$penalties
	}



ideal = function(hypothesis,rr)
	{
	# Calculates idealised likelihood assuming Q is perfect match
	#
	# Parameters:
	# 	hypothesis: generated by either defense.hypothesis() or 
        #       prosecution.hypothesis()
	#	rr: relatedness arguments from args
	ideal.match = 1
	for(j in 1:ncol(hypothesis$cspProfile))
		{
		af = hypothesis$alleleDb[j][[1]]
		kn = hypothesis$queriedProfile[,j][[1]]
		p1 = af[row.names(af)==kn[1],1]
		p2 = af[row.names(af)==kn[2],1]
		ideal.match = ideal.match/(rr[2] + rr[1]*(p1+p2)/2 + (1-sum(rr))*p1*p2*(1+(kn[1]!=kn[2])))
		}
	return(ideal.match)
	}

		

calc.dropout = function(results, hypothesis)
	{
	# Calculates dropout rates for every contributor subject to dropout and for every replicate
	#
	# Parameters:
	# 	hypothesis: generated by either defense.hypothesis() or 
        #       prosecution.hypothesis()
	#	results: results from do.call(optim,params)
	N = nrow(hypothesis$dropoutProfs) + hypothesis$nUnknowns + 1
	# Number of contributors subject to dropout + number of unknowns + 1 (dropin)
	nrep = nrow(hypothesis$cspProfile)
	do = results$par[grep("dropout",names(results$par))]
	rcont = results$par[grep("rcont",names(results$par))]
	rcont = rcontConvert(hypothesis$refIndiv,rcont)
	BB = results$par[grep("tvedebrink",names(results$par))]
	drout = matrix(0,N-1,nrep)
	if(N>1) for(x in 1:(N-1)) for(z in 1:nrep) drout[x,z] = do[z]/(do[z]+rcont[x]^-BB*(1-do[z]))
	return(drout)
	}
	


rcontConvert <- function(refIndiv,rcont) 
	{
	# Convert rcont to full rcont (including ref individual)
	#
	# Parameters:
	# 	refIndiv: reference individual specified in args
	#	rcont: rcont parameters from do.call(optim,params)
	if(refIndiv == 1) rcont = c(1, rcont)
        else if(refIndiv > length(rcont)) rcont = c(rcont, 1)
        else rcont = c(rcont[1:refIndiv-1], 1,
        rcont[refIndiv:length(rcont)])
	return(rcont)
	}



dropDeg <- function(hypothesis,results,dropout,args) 
	{
	# Output tables for dropout and degradation
	#
	# Parameters:
	# 	hypothesis: generated by either defense.hypothesis() or 
        #       prosecution.hypothesis()
	#	results: results from do.call(optim,params)
	#	dropout: dropout estimates generated by calc.dropout()
	#	args: arguments specified by user
	dropoutsLogical = determine.dropout(read.known.profiles(args$refFile),read.csp.profile(args$mixedFile))
	Nknd = length(which(!dropoutsLogical))
	Qdrop = dropoutsLogical[names(dropoutsLogical)==rownames(hypothesis$queriedProfile)]
	nrep = nrow(hypothesis$cspProfile)
	nameQ = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]==TRUE)]
	nameK = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]!=TRUE)]
	# names (including 'Q','K','U')in correct order 
	Names=c()
	Names[length(c(nameQ,nameK))] = paste(nameQ,'(Q)')
	if(length(nameK)>0)for (n in 1:length(nameK)) Names[n]=paste(nameK[n],' (K',n,')',sep='')

	if(hypothesis$hypothesis=="defense") Names[length(c(nameQ,nameK))] = 'X'

	condition = (hypothesis$nUnknowns>0)&(hypothesis$hypothesis=="prosecution")
	if(condition)for(n in 1:hypothesis$nUnknowns)Names = c(Names,paste('U',n,sep=''))
	condition = (hypothesis$nUnknowns>1)&(hypothesis$hypothesis=="defense")
	if(condition)for(n in 1:(hypothesis$nUnknowns-1))Names = c(Names,paste('U',n,sep=''))
	runNames = c();for(rName in 1:nrep)runNames[rName]=paste('Run',rName)

# Table
	h = h1 = round(dropout,4)	
	Loss = Loss1 = round(10^results$par[grep("degradation",names(results$par))],4)
	if(hypothesis$hypothesis=="prosecution")
		{
		if(Qdrop==F)
			{
			h = rbind(h[0:nrow(hypothesis$dropoutProfs),],0)
			if(hypothesis$nUnknowns>0)
				{
				if(nrep>1) h = rbind(h,h1[(nrow(hypothesis$dropoutProfs)+1):length(Loss1),])
				if(!nrep>1) h = rbind(h,as.matrix(h1[(nrow(hypothesis$dropoutProfs)+1):length(Loss1),]))
				}
			Loss = c(Loss[0:nrow(hypothesis$dropoutProfs)],0)
			if(hypothesis$nUnknowns>0)
				{
				Loss = c(Loss,Loss1[(nrow(hypothesis$dropoutProfs)+1):length(Loss1)])
				}
			}
		}
	if(Nknd>0) for(n in 1:Nknd)
		{
		h = rbind(0,h)
		Loss = c(0,Loss)
		}
	Dropout = format(round(data.frame(h,Loss),3),nsmall=3)
	colnames(Dropout)= c(runNames[1:(nrep)],'Degradation:')
	row.names(Dropout) = Names
	return(Dropout)
	}



outputNames <- function(stain,args,prosecutionHypothesis,caseFolder)
	{
	# Names for output files
	#
	# Parameters:
	#	stain: string with the name of the stain
	#	args: arguments specified by user
	#	prosecutionHypothesis: generated by prosecution.hypothesis()
	#	caseFolder:
	nameQ = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]==TRUE)]
	nameK = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]!=TRUE)]
	nameCode=c()
	for(n in 1:length(c(nameQ,nameK)))
		{
		nameCode=c(nameCode,strsplit(c(nameQ,nameK)[n],'')[[1]][1:2])
		nameCode = paste(nameCode,collapse='')
		}
	version=1
	FN=paste(stain,nameCode,prosecutionHypothesis$nUnknowns,args$ethnic,args$doDropin,version,sep='-')
	pdf.name = paste(FN,'pdf',sep='.')
	RData.name = paste(FN,'RData',sep='.')
	while(pdf.name %in% list.files(caseFolder))
		{
		version=version+1
		FN=paste(stain,nameCode,prosecutionHypothesis$nUnknowns,args$ethnic,args$doDropin,version,sep='-')
		pdf.name = paste(FN,'pdf',sep='.')
		RData.name = paste(FN,'RData',sep='.')
		}
	return(list(pdf.name=pdf.name,RData.name=RData.name))
	}



stateHypotheses <- function(args)
	{
	# Table with hypotheses described
	#
	# Parameters:
	# 	args: arguments specified by user
	HP = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]==TRUE)] # nameQ
	HD = c('Unknown (X)')
	nameK = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]!=TRUE)]
	if(length(nameK)>0)for (x in 1:length(nameK))
		{
		HP = paste(HP,nameK[x],sep=' + ')
		HD = paste(HD,nameK[x],sep=' + ')
		}
	if(args$nUnknowns>0)for (x in 1:args$nUnknowns)
		{
		HP = paste(HP,paste('unknown (U',x,')',sep=''),sep=' + ')
		HD = paste(HD,paste('unknown (U',x,')',sep=''),sep=' + ')
		}
	if (args$doDropin ==T)
		{
		HP = paste(HP,' + Dropin')
		HD = paste(HD,' + Dropin')
		}
	hypothesis = t(data.frame(HP,HD))
	colnames(hypothesis) = NA
	row.names(hypothesis) = c('Prosecution(HP)','Defence(HD)')
	return(hypothesis)
	}




alleleReport <- function(args,prosecutionHypothesis) 
	{
	#  Make tables for output: CSP alleles (alleles), 
	# attribution to knowns (summary), attributable 
	# replicated alleles (otherRep), unattributable
	# unreplicated alleles (otherUnrep), approximate
	# representation (estimates), and the size for tables (tablesize) 
	#
	# Parameters:
	# 	args: arguments specified by user
	# 	prosecutionHypothesis: generated by prosecution.hypothesis()
	nameQ = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]==TRUE)]
	nameK = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]!=TRUE)]
	onlyCSP <- read.csp.profile(args$mixedFile)
	onlyUnc <- read.unc.profile(args$mixedFile)
	# Transform CSP into 'cprofs' format
	nrep = nrow(prosecutionHypothesis$cspProfile)
	cprofs = as.list(colnames(prosecutionHypothesis$cspProfile)) # creates a list of all loci
	for(locus in 1:length(cprofs))
		{	
		cprofs[[locus]]=list()  # creates a list of reps in each loci
		for(rep in 1:nrep)
			{
			cprofs[[locus]][[rep]]=list(csp=NULL,unc=NULL) # fills it with NULL csp and unc
			if (is.na(onlyCSP[rep,locus])) 
				{			
				cprofs[[locus]][rep]=list(NULL) # NAs must be formatted differently
				} else {
				csp.value = gsub(' ','', paste(unlist(onlyCSP[rep,locus]),collapse=","))
				if(csp.value!='')cprofs[[locus]][[rep]]$csp = strsplit(csp.value,',')[[1]] # values into csp 
				unc.value = gsub(' ','', paste(unlist(onlyUnc[rep,locus]),collapse=","))
				if(unc.value!='')cprofs[[locus]][[rep]]$unc = strsplit(unc.value,',')[[1]] # values into unc 
				}
			}
		}
	# allele table for CSP
	nloc = length(cprofs); nrep = length(cprofs[[1]])
	alleles = array(0,c(2*nrep,nloc))
	cspCombined.all = replicated.all = unreplicated.all = vector('list',nloc)
	for(l in 1:nloc){ 
		cspCombined = c()
		for(r in 1:nrep){
			if(is.null(cprofs[[l]][[r]])){
				alleles[2*r-1,l]='NA'
				alleles[2*r,l] ='NA'
				}
			if(!is.null(cprofs[[l]][[r]])){
				alleles[2*r-1,l] = paste(cprofs[[l]][[r]]$csp,collapse=' ')
				alleles[2*r,l] = paste(cprofs[[l]][[r]]$unc,collapse=' ')
				}
			cspCombined=c(cspCombined,cprofs[[l]][[r]]$csp)
			}
		if(!is.null(cspCombined)){
			cspCombined.all[[l]] = cspCombined 
			replicated.all[[l]] = unique(cspCombined[duplicated(cspCombined)])
			unreplicated.all[[l]] = cspCombined[!cspCombined%in%replicated.all[[l]]]}}

	alleleRows = c();for(r in 1:nrep)alleleRows=c(alleleRows,paste('csp',r),paste('unc',r))
	alleles = data.frame(alleles)
	row.names(alleles)=alleleRows
	colnames(alleles)=colnames(onlyCSP)

	# Get table sizes
	CSPtotal = UNCtotal = numeric(nrep)
	for(l in 1:nloc){ 
		for(r in 1:nrep){
			CSPtotal[r] = CSPtotal[r]+length(cprofs[[l]][[r]]$csp)
			UNCtotal[r] = UNCtotal[r]+length(cprofs[[l]][[r]]$unc)
			}
		}
	tablesize = min(1,25/max(c(CSPtotal,UNCtotal)))

	# Generate summary table
	REF = read.known.profiles(args$refFile)
	knownNames = c()
	for (name in nameQ)knownNames =c(knownNames,paste(name,'(Q)'))
	for (name in nameK)knownNames =c(knownNames,paste(name,'(K)'))
	ncont = length(knownNames)
	index = c()
	for (x in c(nameQ,nameK))
		{
		index = c(index,which(row.names(REF)==x))
		}
	known = as.list(colnames(onlyCSP))
	for(locus in 1:length(cprofs))
		{
		known[[locus]] = unlist(REF[index,locus+1]) # converts into a vector
		}
	summary = array(0,c(ncont+1,nloc))
	otherRep = numeric(nloc)
	otherUnrep = numeric(nloc)
	for(l in 1:nloc)
		{ 
		contCombined = c()
		for(c in 1:ncont)
			{
			cont = known[[l]][(2*c-1):(2*c)]
			contCombined = c(contCombined,cont)
			summary[c,l] = paste(paste(cont[cont%in%replicated.all[[l]]],collapse=' '),'{',paste(cont[cont%in%unreplicated.all[[l]]],collapse=' '),'}','[',paste(cont[!cont%in%cspCombined.all[[l]]],collapse=' '),']',sep='')
			}
		# other alleles not found in the cprofs
		unattributable = cspCombined.all[[l]][!cspCombined.all[[l]]%in%contCombined]
		unattributableRep = unique(unattributable[duplicated(unattributable)])
		otherRep[l] = length(unattributableRep)
		unattributableUnrep = unattributable[!unattributable%in%unattributableRep]
		otherUnrep[l] = length(unattributableUnrep)
		summary[dim(summary)[1],l] = paste(paste(unattributableRep,collapse=' '),'{',paste(unattributableUnrep,collapse=' '),'}',sep='')
		}
	summary = data.frame(summary)
	row.names(summary)=c(knownNames,'Unattributable')
	colnames(summary)=colnames(onlyCSP)

	# Generate estimates
	allRepCSP = array(0,c(dim(REF)[1],nrep+1))
	for(person in 1:dim(REF)[1])
		{
		for(rep in 1:nrep)
			{
			representedCSP=c()
			for(locus in 1:length(cprofs))
				{
				tmpalleles = unique(unlist(REF[person,locus+1]))
				if(!is.null(cprofs[[locus]][[rep]]))representedCSP = c(representedCSP,tmpalleles%in%cprofs[[locus]][[rep]]$csp)
				}
			allRepCSP[person,rep] = round(100*sum(representedCSP)/length(representedCSP))
			}
		}
	if(nrep==1)allRepCSP[,nrep+1]= allRepCSP[,nrep]
	if(nrep>1)allRepCSP[,nrep+1]= round(rowSums(allRepCSP)/nrep)
	runNames = c(); for(n in 1:nrep)runNames[n]=paste('run',n)
	estimates = data.frame(allRepCSP,row.names=rownames(REF));colnames(estimates)=c(runNames,'total')
	estimates = estimates[order(estimates[,nrep+1],decreasing=T),]
	names = rownames(estimates)

	return(list(alleles=alleles,tablesize=tablesize,summary=summary,otherRep=otherRep,otherUnrep=otherUnrep,estimates=estimates))
	}







#------------------------------------------
# outputReport()
#------------------------------------------
# Generate output report
outputReport <- function (prosecutionHypothesis,defenseHypothesis, prosecutionResults,defenseResults,args,caseName,stain) 
	{
	# Generate the output report
	#
	# Parameters:
	# 	prosecutionHypothesis: generated by either prosecution.hypothesis()
	# 	defenseHypothesis: generated by either defense.hypothesis()
	# 	prosecutionResults: results from do.call(optim, prosecutionParams)
	# 	defenseResults: results from do.call(optim, defenseParams)
	# 	args: arguments specified by user
	# 	caseName: string with the name of the case
	# 	stain: string with the name of the stain
	library(gplots)
#-------------------------------------------------------------------------------
	# 1. Match probability and dropout probabilities
	# Calculates idealised likelihood assuming Q is perfect match
	ideal.match=ideal(defenseHypothesis,args$relatedness)
	# Calculates dropout rates for every contributor subject to dropout and for every replicate
	hpdrout = calc.dropout(prosecutionResults, prosecutionHypothesis)
	hddrout = calc.dropout(defenseResults, defenseHypothesis)

	endTime = as.character(Sys.time())

#--------------------------------------------------------------------------------
	# 2. Table for reports (alleles)
	alleleTableOut <- alleleReport(args,prosecutionHypothesis)
	tablesize = alleleTableOut$tablesize
	otherBoth = alleleTableOut$otherRep + alleleTableOut$otherUnrep


#--------------------------------------------------------------------------------
	# 2. Table for reports (summary)
	namesQ = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]==TRUE)]
	namesK = rownames(read.known.profiles(args$refFile))[which(read.known.profiles(args$refFile)[,1]!=TRUE)]
	summary <- summary.generator(namesQ,namesK,args)
 	#--------------------------------------------------------------------------------
	# 3. Table for reports (likelihood for each locus)
	prosecuLikes <- locusLikes(prosecutionHypothesis,prosecutionResults)
	defenseLikes <- locusLikes(defenseHypothesis,defenseResults)
	likelihood  = data.frame(signif(prosecuLikes,2),signif(defenseLikes,2),signif(prosecuLikes/defenseLikes,2))
	colnames(likelihood)= c('HP','HD','Ratio')
	row.names(likelihood)= colnames(defenseHypothesis$queriedProfile)

#--------------------------------------------------------------------------------
	# 4. Table for reports (likelihood overall)
	overallLikelihood  = data.frame(signif(10^prosecutionResults$value,2),signif(10^defenseResults$value,2),signif(10^(prosecutionResults$value/defenseResults$value),2),signif(prosecutionResults$value/defenseResults$value,2))
	colnames(overallLikelihood)= c('HP','HD','Ratio','Log Ratio')
	row.names(overallLikelihood)= ''

#--------------------------------------------------------------------------------
	# 5. Table for reports (DROPOUT and DEGRADATION)
	pDropout = dropDeg(prosecutionHypothesis,prosecutionResults,hpdrout,args) 
	dDropout = dropDeg(defenseHypothesis,defenseResults,hddrout,args) 

#--------------------------------------------------------------------------------
	# 6. Table for reports (DROP-IN)
	if(args$doDropin==TRUE)
		{
		pDropin = prosecutionResults$par[grep("dropin",names(prosecutionResults$par))]
		dDropin = defenseResults$par[grep("dropin",names(defenseResults$par))]
		dropin = round(data.frame(pDropin,dDropin,3))
		colnames(dropin) = c('HP','HD')
		row.names(dropin) = ''
		}

#--------------------------------------------------------------------------------
	# 7. Table for reports (SYSTEM INFO)
	operator = data.frame(Sys.info())
	colnames(operator) = 'Operator info'

#--------------------------------------------------------------------------------
	# 8. Table for reports (PARAMETERS)
	CSPname = tail(strsplit(args$mixedFile,split='/')[[1]],1)
	REFname = tail(strsplit(args$refFile,split='/')[[1]],1)
	ALLELEname = ifelse(is.null(args$database),"lgc-allele-freqs-wbp.txt",tail(strsplit(args$databaseFile,split='/')[[1]],1))

	dropoutsLogical = determine.dropout(read.known.profiles(args$refFile),read.csp.profile(args$mixedFile))
	Nknd = length(which(!dropoutsLogical))
	Nkdo = length(which(dropoutsLogical))

	administration = data.frame(
		c(
		caseName,
		stain,
		CSPname,
		REFname,
		ALLELEname,
		args$ethnic,
		#initiated,
		endTime,
		args$adj,
		args$fst,
		args$relatedness[1],
		args$relatedness[2],
		Nknd,
		Nkdo,
		defenseHypothesis$nUnknowns,	
		prosecutionHypothesis$nUnkowns,
		args$doDropin,
		#paste(format(round(start$nupa$do,2),nsmall=2),collapse=' '),
		#paste(format(round(start$depa$do,2),nsmall=2),collapse=' '),
		paste(format(round(prosecutionResults$par[grep("dropout",names(prosecutionResults$par))],2),nsmall=2),collapse=' '),
		paste(format(round(defenseResults$par[grep("dropout",names(defenseResults$par))],2),nsmall=2),collapse=' '),
		paste(format(round(10^prosecutionResults$par[grep("degradation",names(prosecutionResults$par))],2),nsmall=2),collapse=' '),
		#paste(format(round(start$nupa$rcont,2),nsmall=2),collapse=' '),
		#paste(format(round(start$depa$rcont,2),nsmall=2),collapse=' '),
		paste(format(round(prosecutionResults$par[grep("rcont",names(prosecutionResults$par))],2),nsmall=2),collapse=' '),
		paste(format(round(defenseResults$par[grep("rcont",names(defenseResults$par))],2),nsmall=2),collapse=' '),
		paste(format(round(prosecutionResults$par[grep("Adjustment",names(prosecutionResults$par))],2),nsmall=2),collapse=' '),
		paste(format(round(defenseResults$par[grep("Adjustment",names(defenseResults$par))],2),nsmall=2),collapse=' '),
		paste(format(prosecutionResults$counts,nsmall=2),collapse=' '),
		prosecutionResults$convergence,
		prosecutionResults$message,
		paste(format(defenseResults$counts,nsmall=2),collapse=' '),
		defenseResults$convergence,
		defenseResults$message,
		signif(as.numeric(ideal.match),3),
		row.names=NULL)
		)
		
	colnames(administration) = "Parameters"
	rownames(administration) = c(
		'Case:',
		'Stain:',
		'CSP file:',
		'Reference file:',
		'Allele frequency file:',
		'EA ethnic group:',
		#'Time started:',
		'Time finished:',
		'adj:',
		'fst:',
		'rr(1):',
		'rr(2):',
		'Nknd:',
		'Nkdo:',
		'NU+1:',
		'NU:',
		'Drin:',
		#'Initial HP do:',
		#'Initial HD do:',
		'Max HP	do:',
		'Max HD do:',
		#'Max deg:',	
		#'Initial HP rcont:',
		#'Initial HD rcont:',
		'Max HP rcont:',
		'Max HD rcont:',
		'Max HP local adjust:',
		'Max HD local adjust:',
		'Optimisation HP counts:',
		'Optimisation HP convergence:',
		'Optimisation HP message:',
		'Optimisation HD counts:',
		'Optimisation HD convergence:',
		'Optimisation HD message:',
		'Ideal match:')


#-----------------------------------------------------------------------------------
	# 9. State overall general hypothesis
	hypothesisTable <- stateHypotheses(args)

#-----------------------------------------------------------------------------------
	# 10. Nomenclature
	nomenclature = '
	adj:		sampling adjustment parameter
	fst:		coancestry parameter (remote shared ancestry of Q and X).
	rr:		probabilities of X and Q sharing 1 and 2 alleles through
			shared inheritance from recent ancestors such as parents 
			and grandparents; for full sibs, rr[1]=0.5 and rr[2]=0.25.
	Nknd:		number of profiled potential contributors not subject to dropout.
	Nkdo:		number of profiled potential contributors subject to dropout.
	NU+1:		number of unknown contributors under Hd.
	NU:		number of unknown contributors under Hp.
	Drin:   TRUE if dropin is being modelled.'

#-----------------------------------------------------------------------------------
	# 11. Prints report
	size = 1
	hsize = 1.3
	layout(mat = c(1,2,3,4,5,6), heights = c(1,1,3,1,1,3))
	# report pg1
	par(mai = c(0.5,0.5,0.5,0.5))
	par(mai = rep(0.3,times=4))
	textplot(hypothesisTable,valign='top',cex=size)
	title('Hypothesis',cex=hsize)
	textplot(alleleTableOut$alleles,valign='top',cex=tablesize)
	title('Crime scene profiles',cex=hsize)
	textplot(alleleTableOut$summary,valign='top',cex=tablesize)
	title('Summary. {}=unreplicated, []=absent',cex=hsize)
	textplot(t(likelihood),valign='top',cex=size)
	title('likelihood',cex=hsize)
	yaxp=c(0,max(otherBoth),max(otherBoth))
	if(max(otherBoth)==0)yaxp=c(0,1,1)
	barplot(otherBoth,names.arg=colnames(read.csp.profile(args$mixedFile)),yaxp=yaxp,main='Unattributable alleles',ylab='No. alleles')
	barplot(add=T,col='black',otherRep, yaxt='n')
	if(max(otherBoth)>3)abline(h=2,lty=2)
	if(max(otherBoth)>5)abline(h=4,lty=2)
	if(max(otherBoth)>7)abline(h=6,lty=2)
	if(max(otherBoth)>9)abline(h=8,lty=2)
	legend(x=0,y=max(otherBoth),yjust=0,bty='n',c('replicated','unreplicated'),xpd=NA,col=c('black','grey'),pch=c(15,15))

	# report pg2
	par(mfrow= c(6,1),mai = c(0.5,0.5,0.5,0.5))
	par(mfrow= c(6,1),mai = rep(0.3,times=4))
	textplot(t(overallLikelihood),valign='top',cex=size)
	title('Likelihood (overall)',cex=hsize)
	textplot(pDropout,valign='top',cex=size)
	title('HP Drop-out',cex=hsize)
	textplot(dDropout,valign='top',cex=size)
	title('HD Drop-out',cex=hsize)
	textplot(alleleTableOut$estimates,cex=1,valign='top')
	title('Approximate representation %',cex=hsize)
	if(args$doDropin==TRUE)
		{
		textplot(t(dropin),valign='top',cex=size)
		title('Drop-in (overall)',cex=hsize)
		}
	textplot(operator,valign='top',cex=size)
	title('System info',cex=hsize)

	# report pg3
	layout(mat = c(1,2), heights = c(2,1))
	par(mai = c(0.5,0.5,0.5,0.5))
	par(mai = rep(0.3,times=4))
	size = 0.7
	textplot(administration,valign='top',cex=size)
	title('Parameters')
	textplot(nomenclature,valign='top',cex=size)
	title('Nomenclature')
	}


