pack.admin.input.peaks <- function(peaksFile, callsFile, refFile, stutterFile, caseName='dummy',databaseFile=NULL, kit=NULL, outputPath=getwd() ) {
	# Packs and verifies administrative information.
	# Documentation in man directory.
    	paths <- c(peaksFile, refFile) 
	if(!is.null(databaseFile)) paths <- c(databaseFile, paths, recursive=TRUE)
	for(path in paths) {
		if(!file.exists(path))
			stop(paste(path, "does not exist."))
		else { 
			info <- file.info(path)
			if(info$isdir) stop(paste(path, "is not a file."))
      		}
    		} # loop over files.
	if(file.exists(outputPath) & !file.info(outputPath)$isdir) 
	stop(paste(outputPath, " exists and is not a directory."))
	admin <- list( caseName=caseName,
                databaseFile=databaseFile,
                peaksFile=peaksFile,
                refFile=refFile,
                outputPath=outputPath,
		kit=kit )
	return(admin)}

locus.likes.peaks <- function(hypothesis,results,...){
	# Generate locus likelihoods from overall likelihood
	# 	hypothesis: generated by either defence.hypothesis() or 
      #     prosecution.hypothesis()
	# results: results from do.call(optim,params)
	model <- create.likelihood.vectors.peaks(hypothesis)
	arguments <- relistArguments.peaks(results$optim$bestmem, hypothesis, ...)
	likes <- do.call(model,arguments)
	likes <- likes$objectives * likes$penalties
	}


getPeakContributors = function(locusPeaks,locusRefs)
	{
	conts = list()
	for(i in 1:length(locusPeaks))
		{
		conts[[length(conts)+1]] = which(sapply(locusRefs,FUN=function(x) any(x%in%locusPeaks[i])))
		}
	return(conts)
	}

plotline = function(height,size,contributors,colours)
	{
	if(length(contributors)==0) 
		{
		lines(c(size,size),c(0,height),col="black",lwd=3,lend=1)
		} else {
		# solid line
		lines(c(size,size),c(0,height),col=colours[contributors[1]],lwd=3,lend=1)
		if(length(contributors)>1)
			{
			# hexadecimal goes to 15
			max = 15
			# number of contributors at this peak
			ncont = length(contributors)
			# how large we can make each subline
			factor = floor(max/(ncont-1))
			factor = 2
			for(i in 1:(ncont-1))
				{
				# hexadecimal code for lines on/off scheme for each contributor
				lineScheme = paste(c(toString(as.hexmode((ncont-i)*factor)),toString(as.hexmode(i*factor))),collapse="",sep="")
				# plot the subline for this individual
				lines(c(size,size),c(0,height),col=colours[contributors[i+1]],lwd=3,lend=1,lty=lineScheme)
				}
			}
		}
	}


plot.CSP.heights = function(cspFile,refFile=NULL,detectThresh=NULL,stutterThresh=NULL,replicate=1)
	{
	# get CSP
	csp = read.peaks.profile(cspFile)
	# get K profiles
	if(!is.null(refFile)) 
		{
		# get reference profiles
		refs = read.known.profiles(refFile)
		Q = refs[which(unlist(refs[,1])),-1]
		# make Q the first individual
		refIndex = which(unlist(refs[,1]))
		refs = rbind(refs[refIndex,],refs[-refIndex,])
		# colours
		contColours = rainbow(nrow(refs))
		nK = length(contColours)
		}
	# locus names
	loci = rownames(csp$alleles[[replicate]])
	# stutter calls 
	if(!is.null(stutterThresh)) 
		{
		stutters = make.allelic.calls(csp,stutterThresh)
		}
	# set plotting parameters that are constant across loci
	par(mfrow=rep(ceiling(sqrt(nrow(csp$alleles[[replicate]]))),times=2),mar=c(2,2,2,0))
	YLIM = c(0,range(unlist(csp$heights),na.rm=TRUE)[2])
	YLIM = YLIM + c(0,YLIM[2]/10)
	# loop over loci
	for(j in 1:nrow(csp$alleles[[replicate]]))
		{
		# set plotting parameters that are specific to a locus
		XLIM = range(as.numeric(csp$sizes[[replicate]][j,]),na.rm=TRUE)
		XLIM = XLIM + c(-2,2)
		flag = (j-1)%%4==0
		# make an empty plot
		plot(NA,ylim=YLIM,xlim=XLIM,ylab="RFU",xlab="Size",main=rownames(csp$alleles[[replicate]])[j],yaxt=ifelse(flag,'s','n'))
		# add baseline
		abline(h=0)
		# add detection threshold
		if(!is.null(detectThresh)) abline(h=detectThresh,col="red",lty=3)
		if(!is.null(refFile))
			{
			# add which K contributes to each peak
			peakContributors = getPeakContributors(csp$alleles[[replicate]][loci[j],],refs[,loci[j]])
			# add peaks
			mapply(as.numeric(csp$heights[[replicate]][j,]),as.numeric(csp$sizes[[replicate]][j,]),peakContributors,FUN=function(a,b,c) plotline(height=a,size=b,contributors=c,contColours))
			} else {
			mapply(as.numeric(csp$heights[[replicate]][j,]),as.numeric(csp$sizes[[replicate]][j,]),FUN=function(a,b) lines(x=c(b,b),y=c(0,a),col="blue"))
			}
		# add peak labels
		if(is.null(stutterThresh))
			{
			mapply(as.numeric(csp$sizes[[replicate]][j,]),as.numeric(csp$heights[[replicate]][j,]),csp$alleles[[replicate]][j,],FUN=function(x,y,a) text(x,y+(YLIM[2]/12),a,col="blue"))
			} else {
			mapply(as.numeric(csp$sizes[[replicate]][j,]),as.numeric(csp$heights[[replicate]][j,]),csp$alleles[[replicate]][j,],stutters[[replicate]][j,],FUN=function(x,y,a,b) text(x,y+(YLIM[2]/12),a,col=ifelse(b,"blue","gray")))
			}
		}		
	}












