pack.admin.input.peaks <- function(peaksFile, callsFile, refFile, stutterFile, caseName='dummy',databaseFile=NULL, kit=NULL, outputPath=getwd() ) {
	# Packs and verifies administrative information.
	# Documentation in man directory.
    	paths <- c(peaksFile, refFile) 
	if(!is.null(databaseFile)) paths <- c(databaseFile, paths, recursive=TRUE)
	for(path in paths) {
		if(!file.exists(path))
			stop(paste(path, "does not exist."))
		else { 
			info <- file.info(path)
			if(info$isdir) stop(paste(path, "is not a file."))
      		}
    		} # loop over files.
	if(file.exists(outputPath) & !file.info(outputPath)$isdir) 
	stop(paste(outputPath, " exists and is not a directory."))
	admin <- list( caseName=caseName,
                databaseFile=databaseFile,
                peaksFile=peaksFile,
                refFile=refFile,
                outputPath=outputPath,
		kit=kit )
	return(admin)}

locus.likes.peaks <- function(hypothesis,results,...){
	# Generate locus likelihoods from overall likelihood
	# 	hypothesis: generated by either defence.hypothesis() or 
      #     prosecution.hypothesis()
	# results: results from do.call(optim,params)
	model <- create.likelihood.vectors.peaks(hypothesis)
	arguments <- relistArguments.peaks(results$optim$bestmem, hypothesis, ...)
	likes <- do.call(model,arguments)
	likes <- likes$objectives * likes$penalties
	}


plot.CSP.heights = function(cspFile,detectThresh=NULL)
	{
	csp = read.peaks.profile(cspFile)
	# loop over replicates
	for(i in 1:length(csp$alleles))
		{
		# set plotting parameters that are constant across loci
		par(mfrow=rep(ceiling(sqrt(nrow(csp$alleles[[i]]))),times=2),mar=c(2,2,2,0))
		YLIM = c(0,range(unlist(csp$heights),na.rm=TRUE)[2])
		YLIM = YLIM + c(0,YLIM[2]/10)
		# loop over loci
		for(j in 1:nrow(csp$alleles[[i]]))
			{
			# set plotting parameters that are specific to a locus
			XLIM = range(as.numeric(csp$sizes[[i]][j,]),na.rm=TRUE)
			XLIM = XLIM + c(-2,2)
			flag = (j-1)%%4==0
			# make an empty plot
			plot(NA,ylim=YLIM,xlim=XLIM,ylab="RFU",xlab="Size",main=rownames(csp$alleles[[i]])[j],yaxt=ifelse(flag,'s','n'))
			# add baseline
			abline(h=0)
			# add detection threshold
			if(!is.null(detectThresh)) abline(h=detectThresh,col="red",lty=3)
			# add peaks
			mapply(as.numeric(csp$sizes[[i]][j,]),as.numeric(csp$heights[[i]][j,]),FUN=function(x,y) lines(c(x,x),c(0,y),col="blue"))
			# add peak labels
			mapply(as.numeric(csp$sizes[[i]][j,]),as.numeric(csp$heights[[i]][j,]),csp$alleles[[i]][j,],FUN=function(x,y,a) text(x,y+(YLIM[2]/12),a,col="blue"))
			}
		
		}
	}
